### ISSUE TITLE
Firefox 128 

### ISSUE THREAD

**Issue by 55trucker** [Aris-t2/NoiaButtons#10]
Hi there Aris:

will  your latest work here on the Noia buttons function inside Firefox 128 64 bit?

I've been using your work in an older 32bit esr Firefox 115 & the entire project runs flawlessly, I'm now using Firefox 128 64BIT on another 64 bit W10 pc, I've copied the entire profile folder for the 32bit operating system to the 64 bit Roaming Mozilla profile folder 
& nothing is doing what I anticipated the transfer to do.

any suggestions?

thx

**Comment by Aris-t2** [comment]
Yes, NoiaButtons code works fine on Firefox 128+(32/64 Bit):
![image](https://github.com/user-attachments/assets/4ab1469f-9837-4a3c-bb54-0936de6ddb40)

**Comment by 55trucker** [comment]
Ok, thx, I'm doing something wrong or I've overlooked one of the steps

**Comment by 55trucker** [comment]
Found my error, got ahead of myself & overlooked making the change in the properties of the browser to allow custom changes to take place.

Here's another question...if I want to alter the toolbar background color to something darker gray (such as the original Noia background color...what color code formula does one use to replace what is presently installed?,,,the toolbar color is far too brown in shade & not enough of the Noia gray..

thx

**Comment by 55trucker** [comment]
The 2 basic colors seem to be CCCCCC & EEEEEE in a linear-gradient,

trying to achieve a more darker bluish gray tint to the background, this is the original Noia moon theme that is still available in Pale moon

![Original Noia Default background program color scheme](https://github.com/user-attachments/assets/f50af035-b952-488d-b063-47a56c2a48cc)

**Comment by 55trucker** [comment]
Getting the hang of this custom css coding to achieve what one is looking for. I've got the background pretty close to what I am looking for, it took approx 5 hours of searching html color code to enter the proper code to change the background colors.
I still want to address the shade for all of the drop-down menus that are not displaying in the same gray as the toolbars, just getting a solid white background.

What is the procedure for entering the correct script to change the menu shade to the same as the toolbar shade?

I came across this tutorial on using userchrome... it has a lengthy section on the menu shades, what do I do to enter this script into the css I am using for  my project?

thx

https://www.userchrome.org/what-is-userchrome-css.html

![Firefox custom Noia theme progress](https://github.com/user-attachments/assets/455eed12-f3b6-491a-b61e-b588e8164497)

**Comment by 55trucker** [comment]
Is there anything at all I can make use of from your old Noia 4 theme you created years ago to enter into the userChrome.css file to make small cosmetic changes to the Firefox appearance?

drop-down menus left side gradient margin, main screen right side scrollbar color?

**Comment by Aris-t2** [comment]
If you now, what you are looking for, you can download the last available Noia 4 theme files from here https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.7.3 and unpack them. Going through the files you might find something useful.

**Comment by 55trucker** [comment]
Hi there!

I have the complete last theme you produced back in 2014, version 1.8.9 for Firefox (which also worked in later versions of Pale Moon),

I already *opened* it up to get a look at all of the individual css files, images, etc.

For me this is a challenge as I'm not sure what particular css file does what & if an image file has to be included with that css file & entering those into the major userChrome (where I have already populated it) file OR if they can be utilized in a standalone xxxxx.css file and merged in an *import* fashion.

I've got more than half the project done, I still want to add the left side *glossy*margin for the context menus, the Noia main screen right side scrollbar design, add the *shadow* around the context menus, alter the color of the open tabs to a darker Royal Blue color etc. 

I'll gladly give all of this back to you completed if someone out there wants the complete Noia look again for Firefox. 


     On Friday, August 23, 2024 at 08:47:41 a.m. EDT, Aris ***@***.***> wrote:  
 
 


If you now, what you are looking for, you can download the last available Noia 4 theme files from here https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.7.3 and unpack them. Going through the files you might find something useful.

**Comment by 55trucker** [comment]
One can see the glossy margin is not yet there in the Firefox project, one can also see the mild shadow around the Pale Moon context menu

![Firefox incomplete Noia look glossy margin missing](https://github.com/user-attachments/assets/7b78ea64-7738-4e41-ae12-da8fb788edee)

![Noia Theme for Pale Moon left side glossy margin](https://github.com/user-attachments/assets/3118bf4c-f5d9-40b5-a5c6-7d684fb648ce)

**Comment by Aris-t2** [comment]
menuback.png: ![menuback](https://github.com/user-attachments/assets/b35921c9-5a8c-4ec6-b6cd-4b3206b226cf)
[menuback.zip](https://github.com/user-attachments/files/16730453/menuback.zip)

CSS:
```css
.menupopup-arrowscrollbox {
  appearance: none !important;
  background: url(./menuback.png) repeat-y #dadce4 !important;
}

  @media (-moz-platform: linux) or (-moz-platform: windows) {
    --panel-shadow-margin: 0 !important;
  }
  
  menupopup {
  --panel-padding: 0 !important;

  @media (-moz-platform: windows) {

    > menu,
    > menuitem {
      padding-inline-start: 2px !important;
    }
  }
}
```

**Comment by 55trucker** [comment]
Thx again for your valuable assistance, the chrome is populated like this....


```css
@import url(userChrome_Fx56_bookmark_icons.css);


/*===============================================================================
  Code mostly taken from 'NoiaButtons' add-on
  Github: https://github.com/aris-t2/noiabuttons


  NoiaButtons CSS for Firefox 111+ 
  Version 3.0.1 


  Last version compatible with Firefox 60-88 is v1.1.5 
  https://github.com/Aris-t2/NoiaButtons/releases/tag/1.1.5

  Last version compatible with Firefox 89-107 is v2.0.1 
  https://github.com/Aris-t2/NoiaButtons/releases/tag/2.0.1

  Last version compatible with Firefox 107-111 is v2.0.3
  https://github.com/Aris-t2/NoiaButtons/releases/tag/2.0.3

  ===============================================================================

  README
  
  Firefox requires the following preference to be enabled for custom styles to be loaded:
  
    'about:config > toolkit.legacyUserProfileCustomizations.stylesheets > true'
  
  Firefox preferences can be accessed by typing 'about:config' into the url bar.
  
  ===============================================================================
  
  ======
  README
  ======

  To find the profile folder type `about:support` into url bar and navigate to: 
  'Profile Folder > Open Folder'
  
  Create a /chrome/ (chrome) directory btw. folder inside the profile folder you just opened and
  paste projects files and folders into it, so it looks like this:
  
  /chrome/css/
  /chrome/images/
  /chrome/userChrome.css

  ENABLING/DISABLING options:
  To activate an option: remove /* before @import
  To deactivate an option: add /* before @import
  
*/


/* Icons for default browser buttons 
   [!] only use one at a time
*/
@import "./css/toolbar_buttons_noia.css"; /**/
/* @import "./css/toolbar_buttons_firefox1.css"; /**/
/* @import "./css/toolbar_buttons_firefox2.css"; /**/
/* @import "./css/toolbar_buttons_firefox3.css"; /**/
/* @import "./css/toolbar_buttons_firefox3aero.css"; /**/


/* Shrink icons on hover */
@import "./css/toolbar_buttons_reduce_size_on_hover.css"; /**/


/* Icon size on navigation toolbar (auto: compact=22/normal=30/touch=36)
   [!] only use one at a time
*/
  @import "./css/toolbar_buttons_size_on_navbar_auto.css"; /**/
/* @import "./css/toolbar_buttons_size_on_navbar_18px.css"; /**/
/* @import "./css/toolbar_buttons_size_on_navbar_24px.css"; /**/
/* @import "./css/toolbar_buttons_size_on_navbar_30px.css"; /**/
/* @import "./css/toolbar_buttons_size_on_navbar_36px.css"; /**/


/* Location bar & search bar: Noia icon for 'go buttons' */
   @import "./css/locationbar_searchbar_go_button.css"; /**/


/* 'Light' and 'Dark' toolbar and tabs themes + 'tabs not on top' (known from "Noia" themes)
   [!] only use one at a time
*/
  /* import "./css/noiaui_light.css"; /**/  /* Light theme */
  @import "./css/noiaui_light_tabs_below_navigation_toolbar.css"; /**/  /* Light theme + 'tabs not on top' */
 /* @import "./css/noiaui_dark.css"; /**/  /* Dark theme*/
 /* @import "./css/noiaui_dark_tabs_below_navigation_toolbar.css"; /**/  /* Dark theme + 'tabs not on top' */

 
/* Alternative tab colors for above's 'Light' and 'Dark' themes
   [!] only use one at a time*/

/* @import "./css/noiaui_light_alternative_tabs.css"; /**/
/* @import "./css/noiaui_dark_alternative_tabs.css"; /**/


/* Separator between nav-bar and bookmarks toolbar for above's 'Light' and 'Dark' themes
   [!] only use one at a time
*/
 /* @import "./css/noiaui_light_separators_between_toolbars.css"; /**/
    @import "./css/noiaui_dark_separators_between_toolbars.css"; /**/

:root {
  --tab-min-height: 24px !important;
}

#main-window:not([chromehidden*="toolbar"])[uidensity="compact"] #navigator-toolbox {
  padding-bottom: calc(2px + var(--tab-min-height)) !important;
}

#main-window:not([chromehidden*="toolbar"]):not([uidensity="compact"]):not([uidensity="touch"]) #navigator-toolbox {
  padding-bottom: calc(7px + var(--tab-min-height)) !important;
}

#main-window:not([chromehidden*="toolbar"])[uidensity="touch"] #navigator-toolbox {
  padding-bottom: calc(7px + var(--tab-min-height)) !important;
}

#TabsToolbar {
  height: calc(7px + var(--tab-min-height)) !important;


}

/*** Photon-like Menu Colors (14 Jan 2022) ***/

/* Bookmarks Toolbar folders */
#PersonalToolbar menupopup,
/* Right-click context menus */
#mainPopupSet menupopup,
/* Top menu bar on Windows (not sure about others) */
#toolbar-menubar menupopup,
/* Sidebar/Library bookmark/history context menus */
#placesContext,
/* Address bar context menu (2021-10-25) */
#urlbar-input-container menupopup,
/* Various toolbar drop-down panels (Fx96) */
#back-button menupopup, #forward-button menupopup,
#identity-popup, #appMenu-popup, #downloadsPanel, #BMB_bookmarksPopup {
  /* Text color */
  --menu-color: #000 !important;
  --arrowpanel-color: #000 !important;
  --panel-color: #000 !important;
  /* Background color */
  --menu-background-color:  #CFD2DD !important;
  --arrowpanel-background: #CFD2DD !important;
  --panel-background: #CFD2DD !important;
  /* Border color (if any) */
  --menu-border-color: threedshadow !important;
  --arrowpanel-border-color: threedshadow !important;
  --panel-border-color: threedshadow !important;
  /* Hovered/expanded item background color */
  --menuitem-hover-background-color: #e0e0e6 !important;
  --button-hover-bgcolor: #e0e0e6 !important;
  /* Disabled items text color and hovered background */
  --menu-disabled-color: rgba(21, 20, 26, 0.4) !important;
  --menuitem-disabled-hover-background-color: rgba(224, 224, 230, 0.4) !important;
}

/*** Tighten up drop-down/context/popup menu spacing (8 Sep 2021) ***/

menupopup:not(.in-menulist) > menuitem, 
menupopup:not(.in-menulist) > menu {
  padding-block: 3px !important; /* reduce to 3px, 2px, 1px or 0px as needed */ 
  min-height: unset !important; /* v92.0 - for padding below 4px */
}

.menupopup-arrowscrollbox {
    margin: 5px;
    box-shadow: 0 0 5px hsla(0,0%,0%,2.5) !important;
    border: none !important;
}

.menupopup-arrowscrollbox {
  appearance: none !important;
  background: url(./menuback.png) repeat-y #dadce4 !important;
}

  @media (-moz-platform: linux) or (-moz-platform: windows) {
    --panel-shadow-margin: 0 !important;
  }
  
  menupopup {
  --panel-padding: 0 !important;

  @media (-moz-platform: windows) {

    > menu,
    > menuitem {
      padding-inline-start: 2px !important;

}

/* Firefox userChrome.css */

menuitem#bookmarksShowAll {
  padding-left: 26px !important;
}

menuitem#menu_bookmarkThisPage,
menuitem#menu_searchBookmarks,
menuitem#menu_bookmarkAllTabs {
  padding-left: 26px !important;

}

```

Morat over on the Mozilla forum was good enough lend a hand with a few details where the menu context padding alignment was concerned, I still am having a difficult time understanding the *talk* of the script........ but I take it that you can look at all of this & know immediately what each entry does,

I'm still not finished......

**Comment by 55trucker** [comment]
Here is the noiaui_light_tabs_below_navigation_toolbar file........
I darkened the background colors for all the bars.......


```css
@import "./noiaui_light.css";

/* colors*/
#main-window #navigator-toolbox #nav-bar {
  background: linear-gradient(#989CA8,#EEEEEE) !important;
}

#main-window #navigator-toolbox #TabsToolbar {
  appearance: none !important;
  background: linear-gradient(grey,#ffffff 1px,#989CA8,#ffffff) !important;
}

#navigator-toolbox {
  background: linear-gradient(#989CA8,#CCCCCC) !important;
}

/* use caption buttons offered for lw-themes */
.titlebar-button {
  -moz-context-properties: unset !important;
}
.titlebar-min {
  list-style-image: url(chrome://browser/skin/window-controls/minimize-themes.svg) !important;
}
.titlebar-max {
  list-style-image: url(chrome://browser/skin/window-controls/maximize-themes.svg) !important;
}
.titlebar-restore {
  list-style-image: url(chrome://browser/skin/window-controls/restore-themes.svg) !important;
}
.titlebar-close {
  list-style-image: url(chrome://browser/skin/window-controls/close-themes.svg) !important;
}

/* tabs not on top mode */
#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar, 
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#TabsToolbar{
  padding-inline-start: 0px !important;
}

#main-window[tabsintitlebar][sizemode="normal"]:not([inFullscreen]) #TabsToolbar {
  margin-top: 0px !important;
  /*border-left: 1px solid #5f7181 !important;
  border-right: 1px solid #5f7181 !important;*/
}

#TabsToolbar{
  margin-bottom: 0px !important;
  /*border-bottom: 1px solid #5f7181 !important;*/
}

#main-window:not([inFullscreen="true"])[tabsintitlebar] #TabsToolbar{
  margin-inline-end: 0px !important;
}

#main-window[tabsintitlebar] #TabsToolbar .titlebar-placeholder{
  visibility: collapse !important;
}

#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive="true"],
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] {
  margin-top: 21px !important;
}

/**/
#main-window[tabsintitlebar][chromehidden~="menubar"] #toolbar-menubar ~ #TabsToolbar,
#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive] ~ #TabsToolbar {
  padding-top: 0px !important;
}

/* Add 4px extra margin on top of the tabs toolbar on Windows 7. */
@media (-moz-os-version: windows-win7) {
  #main-window[tabsintitlebar][chromehidden~="menubar"] #toolbar-menubar ~ #TabsToolbar,
  #main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive] ~ #TabsToolbar {
    padding-top: 0px !important;
  }
}

#tabbrowser-tabs .tab-drop-indicator {
  margin-bottom: 0px !important;
}

#PersonalToolbar:-moz-lwtheme,
#nav-bar:-moz-lwtheme {
  background-image: none !important;
  box-shadow: none !important;
  border-top: none !important;
  border-bottom: none !important;
}

/* remove tab fog */
#TabsToolbar:not(:-moz-lwtheme),
#TabsToolbar:not(:-moz-lwtheme)::before,
#TabsToolbar:not(:-moz-lwtheme)::after {
  box-shadow: unset !important;
}

/* remove 'dragging tab' margin/padding nonsense */
#TabsToolbar[movingtab] {
  padding-bottom: unset !important;
}

#TabsToolbar[movingtab] > .tabbrowser-tabs {
  padding-bottom: unset !important;
  margin-bottom: unset !important;
}

#TabsToolbar[movingtab] + #nav-bar {
  margin-top: unset !important;
}

#TabsToolbar {
  position: absolute !important;
  display: block !important;
  bottom: 0 !important;
  width: 100% !important;
}

#tabbrowser-tabs {
  width: 100% !important;
}

/* move caption buttons to windows top right position */
#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container {
  position: fixed !important;
  right: 0 !important;
  visibility: visible !important;
  display: block !important;
}

/* caption button position in maximized mode after moving to the top */
#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container,
#main-window[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen="true"]) #TabsToolbar .titlebar-buttonbox-container {
  top: 0px !important;
}


/* Windows *//*
@media (-moz-platform: windows-win10), (-moz-platform: windows-win8), (-moz-platform: windows-win7), (-moz-os-version:windows-win10), (-moz-os-version:windows-win8), (-moz-os-version:windows-win7) {
	#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container	{
	  top: 1px !important;
	}
	#main-window[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container {
	  top: 8px !important;
	}
}

/* Windows 7 extra tweaks *//*
@media (-moz-platform: windows-win7), (-moz-os-version: windows-win7) {
  @media all and (-moz-windows-compositor) {
	#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container {
	  display: none !important;
	}
  }
  @media not all and (-moz-windows-compositor) {
	#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container {
	  top: -2px !important;
	}
	#main-window[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container {
	  top: 0px !important;
	}
	#main-window[tabsintitlebar]:not([inDOMFullscreen="true"]) #toolbar-menubar[autohide="true"]:not([inactive="true"]) ~ #TabsToolbar .titlebar-buttonbox-container {
	  display: none !important;
	}
  }
}

/* Windows 10 extra tweaks *//*
@media (-moz-platform: windows-win10), (-moz-os-version: windows-win10) {
  #main-window:not([tabsintitlebar]) menubar > menu:not(:-moz-lwtheme):hover:not([disabled="true"]),
  #main-window:not([tabsintitlebar]) menubar > menu:not(:-moz-lwtheme)[_moz-menuactive="true"]:not([disabled="true"]) {
	background-color: Highlight !important;
	color: HighlightText !important;
  }
}

/* tweaks for fullscreen mode */
#main-window[tabsintitlebar][sizemode="fullscreen"] #toolbar-menubar[autohide="true"] ~ #TabsToolbar .titlebar-buttonbox-container,
#main-window[tabsintitlebar][sizemode="fullscreen"] #navigator-toolbox #PanelUI-button,
#main-window #TabsToolbar #window-controls {
  display: none !important;
}

/* hide non-required items */
#TabsToolbar .private-browsing-indicator,
#TabsToolbar #window-controls,
#TabsToolbar *[type="caption-buttons"],
#TabsToolbar *[type="pre-tabs"],
#TabsToolbar *[type="post-tabs"] {
  display: none !important;
}

/* adjust tabs toolbar padding */
#main-window:is([sizemode="normal"],[sizemode="maximized"],[sizemode="fullscreen"]) #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[tabsintitlebar]:is([sizemode="normal"],[sizemode="maximized"],[sizemode="fullscreen"]) #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window:is([sizemode="normal"],[sizemode="maximized"],[sizemode="fullscreen"]) #navigator-toolbox #TabsToolbar,
#main-window[tabsintitlebar]:is([sizemode="normal"],[sizemode="maximized"],[sizemode="fullscreen"]) #navigator-toolbox #TabsToolbar {
 padding-inline-start: 0px !important;
 margin-inline-start: 0px !important;
}

/* hide line above navigation toolbar appearing in some cases */
#main-window:not([tabsintitlebar]) #nav-bar,
#main-window:not([tabsintitlebar]) #navigator-toolbox {
  border-top: 0 !important;
  box-shadow: unset !important;
}

/* disable Mozillas tab jumping nonsense when moving tabs */
#navigator-toolbox[movingtab] > #titlebar > #TabsToolbar {
  padding-bottom: unset !important;
}
#navigator-toolbox[movingtab] #tabbrowser-tabs {
  padding-bottom: unset !important;
  margin-bottom: unset !important;
}
#navigator-toolbox[movingtab] > #nav-bar {
  margin-top: unset !important;
}

#TabsToolbar {
  min-height: 0 !important;
  height: calc(1px + var(--tab-min-height)) !important;
  max-height: unset !important;
}

#navigator-toolbox {
  position: relative;
}

#main-window:not([chromehidden*="toolbar"])[uidensity="compact"] #navigator-toolbox {
  padding-bottom: 34px !important;
}

#main-window:not([chromehidden*="toolbar"]):not([uidensity="compact"]):not([uidensity="touch"]) #navigator-toolbox {
  padding-bottom: 42px !important;
}

#main-window:not([chromehidden*="toolbar"])[uidensity="touch"] #navigator-toolbox {
  padding-bottom: 46px !important;
}

#TabsToolbar {
  min-height: 0 !important;
  height: calc(6px + var(--tab-min-height)) !important;
  max-height: unset !important;
}

```
